import dataclasses
from typing import Dict

from OCR import CardLayout, ImageArea
from OCR.ParseSettings import ParseSettingConstants, ParseSettingsPresets
from OCR.ParseSettings.LabelParsingMethods import LABEL_PARSING_METHODS
from OCR.ParseSettings.ParseSettings import ParseSettings

PARSE_SETTINGS_BY_ID: Dict[int, ParseSettings] = {
	676: ParseSettingsPresets.DEFAULT_ENCHANTED_PARSE_SETTINGS,
	677: ParseSettingsPresets.DEFAULT_ENCHANTED_PARSE_SETTINGS,
	678: ParseSettingsPresets.DEFAULT_ENCHANTED_PARSE_SETTINGS,
	679: ParseSettingsPresets.DEFAULT_ENCHANTED_PARSE_SETTINGS,
	680: ParseSettingsPresets.DEFAULT_ENCHANTED_PARSE_SETTINGS,
	681: ParseSettingsPresets.DEFAULT_ENCHANTED_PARSE_SETTINGS,
	954: ParseSettingsPresets.DEFAULT_ENCHANTED_PARSE_SETTINGS,
	1161: dataclasses.replace(ParseSettingsPresets.DEFAULT_NEW_ENCHANTED_PARSE_SETTINGS, typeImageTextColorOverride=ImageArea.TEXT_COLOUR_WHITE),
	1172: dataclasses.replace(ParseSettingsPresets.DEFAULT_NEW_ENCHANTED_PARSE_SETTINGS, isLocationOverride=True),
	1178: dataclasses.replace(ParseSettingsPresets.DEFAULT_NEW_ENCHANTED_PARSE_SETTINGS, isLocationOverride=True),
	1186: dataclasses.replace(ParseSettingsPresets.DEFAULT_NEW_ENCHANTED_PARSE_SETTINGS, hasFlavorTextOverride=False, typeImageTextColorOverride=ImageArea.TEXT_COLOUR_WHITE),
	1187: dataclasses.replace(ParseSettingsPresets.PARSE_SETTINGS_BY_GROUPING["C1"], labelParsingMethod=LABEL_PARSING_METHODS.NONE),
	1191: ParseSettings(labelParsingMethod=LABEL_PARSING_METHODS.DEFAULT, textboxLeftOffset=ParseSettingConstants.OPTIONAL_TEXTBOX_OFFSET, getIdentifierFromCard=True),
	1199: dataclasses.replace(ParseSettingsPresets.PARSE_SETTINGS_BY_GROUPING["C1"], textboxLeftOffset=36),
	1197: dataclasses.replace(ParseSettingsPresets.PARSE_SETTINGS_BY_GROUPING["C1"], textboxLeftOffset=39),
	1405: dataclasses.replace(ParseSettingsPresets.PARSE_SETTINGS_FOR_ENCHANTED_BY_SET["6"], typeImageTextColorOverride=ImageArea.TEXT_COLOUR_WHITE),
	1406: dataclasses.replace(ParseSettingsPresets.PARSE_SETTINGS_FOR_ENCHANTED_BY_SET["6"], isLocationOverride=True),
	1407: dataclasses.replace(ParseSettingsPresets.PARSE_SETTINGS_FOR_ENCHANTED_BY_SET["6"], typeImageTextColorOverride=ImageArea.TEXT_COLOUR_WHITE),
	1412: dataclasses.replace(ParseSettingsPresets.PARSE_SETTINGS_FOR_ENCHANTED_BY_SET["6"], labelParsingMethod=LABEL_PARSING_METHODS.NONE),
	1415: dataclasses.replace(ParseSettingsPresets.PARSE_SETTINGS_FOR_ENCHANTED_BY_SET["6"], labelParsingMethod=LABEL_PARSING_METHODS.NONE),
	1418: dataclasses.replace(ParseSettingsPresets.PARSE_SETTINGS_FOR_ENCHANTED_BY_SET["6"], labelParsingMethod=LABEL_PARSING_METHODS.NONE),
	1421: dataclasses.replace(ParseSettingsPresets.PARSE_SETTINGS_FOR_ENCHANTED_BY_SET["6"], isLocationOverride=True),
	1430: dataclasses.replace(ParseSettingsPresets.DEFAULT_PARSE_SETTINGS, textboxLeftOffset=24),
	1431: dataclasses.replace(ParseSettingsPresets.DEFAULT_PARSE_SETTINGS, textboxLeftOffset=24),
	1432: ParseSettings(textboxLeftOffset=0, labelParsingMethod=LABEL_PARSING_METHODS.DEFAULT, getIdentifierFromCard=True),
	1429: dataclasses.replace(ParseSettingsPresets.DEFAULT_NEW_ENCHANTED_PARSE_SETTINGS, hasFlavorTextOverride=False),
	1638: dataclasses.replace(ParseSettingsPresets.DEFAULT_NEW_ENCHANTED_PARSE_SETTINGS, typeImageTextColorOverride=ImageArea.TEXT_COLOUR_WHITE_LIGHT_BACKGROUND),
	1641: dataclasses.replace(ParseSettingsPresets.DEFAULT_NEW_ENCHANTED_PARSE_SETTINGS, isItemOverride=True),
	1643: dataclasses.replace(ParseSettingsPresets.DEFAULT_NEW_ENCHANTED_PARSE_SETTINGS, typeImageTextColorOverride=ImageArea.TEXT_COLOUR_WHITE_LIGHT_BACKGROUND, typeImageLeftOffset=75),
	1662: ParseSettingsPresets.DEFAULT_NEW_ENCHANTED_PARSE_SETTINGS,
	1664: dataclasses.replace(ParseSettingsPresets.PARSE_SETTINGS_BY_GROUPING["C1"], labelParsingMethod=LABEL_PARSING_METHODS.FALLBACK_BY_LINES),
	1869: dataclasses.replace(ParseSettingsPresets.DEFAULT_NEW_ENCHANTED_PARSE_SETTINGS, typeImageTextColorOverride=ImageArea.TEXT_COLOUR_WHITE_LIGHT_BACKGROUND),
	1871: dataclasses.replace(ParseSettingsPresets.DEFAULT_NEW_ENCHANTED_PARSE_SETTINGS, typeImageTextColorOverride=ImageArea.TEXT_COLOUR_WHITE_LIGHT_BACKGROUND),
	1872: dataclasses.replace(ParseSettingsPresets.DEFAULT_NEW_ENCHANTED_PARSE_SETTINGS, typeImageTextColorOverride=ImageArea.TEXT_COLOUR_WHITE_LIGHT_BACKGROUND),
	1893: dataclasses.replace(ParseSettingsPresets.DEFAULT_NEW_ENCHANTED_PARSE_SETTINGS, typeImageTextColorOverride=ImageArea.TEXT_COLOUR_WHITE_LIGHT_BACKGROUND),
	1895: dataclasses.replace(ParseSettingsPresets.PARSE_SETTINGS_BY_GROUPING["D23"], textboxLeftOffset=15),
	1931: dataclasses.replace(ParseSettingsPresets.DEFAULT_PARSE_SETTINGS, labelParsingMethod=LABEL_PARSING_METHODS.FALLBACK_BY_LINES),
	1932: dataclasses.replace(ParseSettingsPresets.DEFAULT_PARSE_SETTINGS, labelParsingMethod=LABEL_PARSING_METHODS.FALLBACK_BY_LINES),
	1933: dataclasses.replace(ParseSettingsPresets.DEFAULT_PARSE_SETTINGS, labelParsingMethod=LABEL_PARSING_METHODS.FALLBACK_BY_LINES, hasFlavorTextOverride=True),
	1934: dataclasses.replace(ParseSettingsPresets.DEFAULT_PARSE_SETTINGS, labelParsingMethod=LABEL_PARSING_METHODS.FALLBACK_BY_LINES),
	1935: dataclasses.replace(ParseSettingsPresets.DEFAULT_PARSE_SETTINGS, labelParsingMethod=LABEL_PARSING_METHODS.FALLBACK_BY_LINES),
	1938: dataclasses.replace(ParseSettingsPresets.DEFAULT_PARSE_SETTINGS, hasCardTextOverride=True),
	2084: dataclasses.replace(ParseSettingsPresets.DEFAULT_PARSE_SETTINGS, hasCardTextOverride=True),
	2141: dataclasses.replace(ParseSettingsPresets.DEFAULT_NEW_ENCHANTED_PARSE_SETTINGS, typeImageTextColorOverride=ImageArea.TEXT_COLOUR_WHITE_LIGHT_BACKGROUND, hasCardTextOverride=True),
	2142: dataclasses.replace(ParseSettingsPresets.DEFAULT_NEW_ENCHANTED_PARSE_SETTINGS, cardLayout=CardLayout.NEW_ENCHANTED_SMALL_TEXTBOX, characterCardLayout=CardLayout.NEW_ENCHANTED_CHARACTER_SMALL_TEXTBOX),
	2143: dataclasses.replace(ParseSettingsPresets.DEFAULT_NEW_ENCHANTED_PARSE_SETTINGS, cardLayout=CardLayout.NEW_ENCHANTED_SMALL_TEXTBOX),
	2145: dataclasses.replace(ParseSettingsPresets.DEFAULT_NEW_ENCHANTED_PARSE_SETTINGS, cardLayout=CardLayout.NEW_ENCHANTED_SMALL_TEXTBOX, characterCardLayout=CardLayout.NEW_ENCHANTED_CHARACTER_SMALL_TEXTBOX),
	2149: dataclasses.replace(ParseSettingsPresets.DEFAULT_NEW_ENCHANTED_PARSE_SETTINGS, cardLayout=CardLayout.NEW_ENCHANTED_SMALL_TEXTBOX, characterCardLayout=CardLayout.NEW_ENCHANTED_CHARACTER_SMALL_TEXTBOX),
	2160: dataclasses.replace(ParseSettingsPresets.DEFAULT_EPIC_PARSE_SETTINGS, labelStartThreshold=180),
	2177: dataclasses.replace(ParseSettingsPresets.DEFAULT_ENCHANTED_PARSE_SETTINGS, labelParsingMethod=LABEL_PARSING_METHODS.FALLBACK_WHITE_ABILITY_TEXT, labelTextColor=ImageArea.TEXT_COLOUR_WHITE_LIGHT_BACKGROUND,
							  thresholdTextColor=ImageArea.TEXT_COLOUR_WHITE_LIGHT_BACKGROUND),
	2178: dataclasses.replace(ParseSettingsPresets.DEFAULT_STANDARDSIZED_ICONIC_PARSE_SETTINGS, colorFilterLowerBound=(0, 0, 120), colorFilterUpperBound=(45, 45, 250), textboxBottomOffset=-60, textboxRightOffset=150,
							  typeImageTextColorOverride=ImageArea.TEXT_COLOUR_BLACK),
	2183: ParseSettingsPresets.DEFAULT_NEW_ENCHANTED_PARSE_SETTINGS,
	2184: dataclasses.replace(ParseSettingsPresets.DEFAULT_PARSE_SETTINGS, textboxLeftOffset=18),
	2188: dataclasses.replace(ParseSettingsPresets.DEFAULT_PARSE_SETTINGS, textboxLeftOffset=24),
	2413: dataclasses.replace(ParseSettingsPresets.DEFAULT_NEW_ENCHANTED_PARSE_SETTINGS, typeImageTextColorOverride=ImageArea.TEXT_COLOUR_WHITE_LIGHT_BACKGROUND),
	2417: dataclasses.replace(ParseSettingsPresets.DEFAULT_NEW_ENCHANTED_PARSE_SETTINGS, cardLayout=CardLayout.NEW_ENCHANTED_SMALL_TEXTBOX),
	2420: dataclasses.replace(ParseSettingsPresets.DEFAULT_NEW_ENCHANTED_PARSE_SETTINGS, cardLayout=CardLayout.NEW_ENCHANTED_SMALL_TEXTBOX),
	2426: dataclasses.replace(ParseSettingsPresets.DEFAULT_NEW_ENCHANTED_PARSE_SETTINGS, cardLayout=CardLayout.NEW_ENCHANTED_SMALL_TEXTBOX),
	2430: dataclasses.replace(ParseSettingsPresets.DEFAULT_ENCHANTED_PARSE_SETTINGS, cardTextHasOutline=True, labelIsDarkerThanBackground=False, labelMaskColor=ParseSettingConstants.BLACK,
							  labelTextColor=ImageArea.TEXT_COLOUR_WHITE_LIGHT_BACKGROUND, thresholdTextColor=ImageArea.TEXT_COLOUR_WHITE_LIGHT_BACKGROUND, forceArtistTextColor=ImageArea.TEXT_COLOUR_WHITE_LIGHT_BACKGROUND),
	2431: dataclasses.replace(ParseSettingsPresets.DEFAULT_ENCHANTED_PARSE_SETTINGS, cardTextHasOutline=True, labelIsDarkerThanBackground=False, labelMaskColor=ParseSettingConstants.BLACK,
							  labelTextColor=ImageArea.TEXT_COLOUR_WHITE_LIGHT_BACKGROUND, thresholdTextColor=ImageArea.TEXT_COLOUR_WHITE_LIGHT_BACKGROUND),
	2432: dataclasses.replace(ParseSettingsPresets.PARSE_SETTINGS_BY_GROUPING["P3"], forceArtistTextColor=ImageArea.TEXT_COLOUR_WHITE_LIGHT_BACKGROUND),
	2433: dataclasses.replace(ParseSettingsPresets.DEFAULT_PARSE_SETTINGS, textboxLeftOffset=15),
	2435: dataclasses.replace(ParseSettingsPresets.PARSE_SETTINGS_BY_GROUPING["P3"], forceArtistTextColor=ImageArea.TEXT_COLOUR_WHITE_LIGHT_BACKGROUND),
	2436: dataclasses.replace(ParseSettingsPresets.PARSE_SETTINGS_BY_GROUPING["P3"], forceArtistTextColor=ImageArea.TEXT_COLOUR_WHITE_LIGHT_BACKGROUND),
	2437: dataclasses.replace(ParseSettingsPresets.PARSE_SETTINGS_BY_GROUPING["P3"], forceArtistTextColor=ImageArea.TEXT_COLOUR_WHITE_LIGHT_BACKGROUND),
	2439: dataclasses.replace(ParseSettingsPresets.PARSE_SETTINGS_BY_GROUPING["P3"], labelIsDarkerThanBackground=False, labelTextColor=ImageArea.TEXT_COLOUR_BLACK, labelMaskColor=ParseSettingConstants.BLACK, thresholdTextColor=ImageArea.TEXT_COLOUR_WHITE),
	2440: dataclasses.replace(ParseSettingsPresets.PARSE_SETTINGS_BY_GROUPING["P3"], labelIsDarkerThanBackground=False, labelTextColor=ImageArea.TEXT_COLOUR_BLACK, labelMaskColor=ParseSettingConstants.BLACK, thresholdTextColor=ImageArea.TEXT_COLOUR_WHITE),
	2441: dataclasses.replace(ParseSettingsPresets.PARSE_SETTINGS_BY_GROUPING["P3"], labelIsDarkerThanBackground=False, labelTextColor=ImageArea.TEXT_COLOUR_BLACK, labelMaskColor=ParseSettingConstants.BLACK, thresholdTextColor=ImageArea.TEXT_COLOUR_WHITE),
	2442: dataclasses.replace(ParseSettingsPresets.PARSE_SETTINGS_BY_GROUPING["P3"], labelIsDarkerThanBackground=False, labelTextColor=ImageArea.TEXT_COLOUR_BLACK, labelMaskColor=ParseSettingConstants.BLACK, thresholdTextColor=ImageArea.TEXT_COLOUR_WHITE),
	2443: dataclasses.replace(ParseSettingsPresets.PARSE_SETTINGS_BY_GROUPING["P3"], labelIsDarkerThanBackground=False, labelTextColor=ImageArea.TEXT_COLOUR_BLACK, labelMaskColor=ParseSettingConstants.BLACK, thresholdTextColor=ImageArea.TEXT_COLOUR_WHITE),
	2444: ParseSettingsPresets.DEFAULT_NEW_ENCHANTED_PARSE_SETTINGS,
	2445: ParseSettingsPresets.DEFAULT_NEW_ENCHANTED_PARSE_SETTINGS,
	2450: dataclasses.replace(ParseSettingsPresets.PARSE_SETTINGS_BY_GROUPING["P3"], labelStartThreshold=100, labelEndThreshold=170, labelTextColor=ImageArea.TEXT_COLOUR_MIDDLE, textboxLeftOffset=10, hasCardTextOverride=True),
	2459: dataclasses.replace(ParseSettingsPresets.DEFAULT_PARSE_SETTINGS, textboxTopOffset=150, textboxBottomOffset=-70),
	2461: dataclasses.replace(ParseSettingsPresets.PARSE_SETTINGS_BY_GROUPING["P3"], labelStartThreshold=100, labelEndThreshold=170, labelTextColor=ImageArea.TEXT_COLOUR_MIDDLE, textboxLeftOffset=10),
	2462: dataclasses.replace(ParseSettingsPresets.PARSE_SETTINGS_BY_GROUPING["P3"], labelStartThreshold=100, labelEndThreshold=170, labelTextColor=ImageArea.TEXT_COLOUR_MIDDLE, textboxLeftOffset=10),
	2669: dataclasses.replace(ParseSettingsPresets.DEFAULT_EPIC_PARSE_SETTINGS, labelStartThreshold=180, labelEndThreshold=185),
	2687: dataclasses.replace(ParseSettingsPresets.DEFAULT_NEW_ENCHANTED_PARSE_SETTINGS, cardLayout=CardLayout.NEW_ENCHANTED_SMALL_TEXTBOX),
	2688: dataclasses.replace(ParseSettingsPresets.DEFAULT_NEW_ENCHANTED_PARSE_SETTINGS, cardLayout=CardLayout.NEW_ENCHANTED_SMALL_TEXTBOX),
	2691: dataclasses.replace(ParseSettingsPresets.DEFAULT_NEW_ENCHANTED_PARSE_SETTINGS, cardLayout=CardLayout.NEW_ENCHANTED_SMALL_TEXTBOX),
	2692: dataclasses.replace(ParseSettingsPresets.DEFAULT_NEW_ENCHANTED_PARSE_SETTINGS, characterCardLayout=CardLayout.NEW_ENCHANTED_CHARACTER_SMALL_TEXTBOX),
	2694: dataclasses.replace(ParseSettingsPresets.DEFAULT_NEW_ENCHANTED_PARSE_SETTINGS, cardLayout=CardLayout.NEW_ENCHANTED_SMALL_TEXTBOX),
	2702: dataclasses.replace(ParseSettingsPresets.DEFAULT_NEW_ENCHANTED_PARSE_SETTINGS, typeImageTextColorOverride=ImageArea.TEXT_COLOUR_WHITE_LIGHT_BACKGROUND),
	2704: dataclasses.replace(ParseSettingsPresets.DEFAULT_STANDARDSIZED_ICONIC_PARSE_SETTINGS, colorFilterLowerBound=(35, 115, 165), colorFilterUpperBound=(140, 222, 245), typeImageTextColorOverride=ImageArea.TEXT_COLOUR_BLACK,
							  textboxRightOffset=100),
	2705: dataclasses.replace(ParseSettingsPresets.DEFAULT_NEW_ENCHANTED_PARSE_SETTINGS, cardLayout=CardLayout.NEW_ENCHANTED_CHARACTER_SMALL_TEXTBOX, characterCardLayout=CardLayout.NEW_ENCHANTED_CHARACTER_SMALL_TEXTBOX,
							  labelIsDarkerThanBackground=False, labelParsingMethod=LABEL_PARSING_METHODS.FALLBACK_BY_LINES, textboxLeftOffset=-75),
	2706: dataclasses.replace(ParseSettingsPresets.DEFAULT_PARSE_SETTINGS, labelIsDarkerThanBackground=False, thresholdTextColor=ImageArea.TEXT_COLOUR_WHITE),
	2707: dataclasses.replace(ParseSettingsPresets.DEFAULT_PARSE_SETTINGS, labelIsDarkerThanBackground=False, thresholdTextColor=ImageArea.TEXT_COLOUR_WHITE),
	2708: dataclasses.replace(ParseSettingsPresets.DEFAULT_PARSE_SETTINGS, labelIsDarkerThanBackground=False, thresholdTextColor=ImageArea.TEXT_COLOUR_WHITE),
	2710: dataclasses.replace(ParseSettingsPresets.DEFAULT_PARSE_SETTINGS, labelIsDarkerThanBackground=False, thresholdTextColor=ImageArea.TEXT_COLOUR_WHITE),
	2714: dataclasses.replace(ParseSettingsPresets.DEFAULT_PARSE_SETTINGS, textboxLeftOffset=15, forceArtistTextColor=ImageArea.TEXT_COLOUR_WHITE_LIGHT_BACKGROUND),
	2715: ParseSettingsPresets.DEFAULT_PARSE_SETTINGS,
	2928: dataclasses.replace(ParseSettingsPresets.DEFAULT_EPIC_PARSE_SETTINGS, labelParsingMethod=LABEL_PARSING_METHODS.FALLBACK_BY_LINES),
	2922: dataclasses.replace(ParseSettingsPresets.DEFAULT_EPIC_PARSE_SETTINGS, labelParsingMethod=LABEL_PARSING_METHODS.FALLBACK_BY_LINES),
	2929: dataclasses.replace(ParseSettingsPresets.DEFAULT_EPIC_PARSE_SETTINGS, labelParsingMethod=LABEL_PARSING_METHODS.FALLBACK_BY_LINES),
	2938: dataclasses.replace(ParseSettingsPresets.DEFAULT_NEW_ENCHANTED_PARSE_SETTINGS, typeImageTextColorOverride=ImageArea.TEXT_COLOUR_WHITE_LIGHT_BACKGROUND),
	2940: dataclasses.replace(ParseSettingsPresets.DEFAULT_NEW_ENCHANTED_PARSE_SETTINGS, cardLayout=CardLayout.NEW_ENCHANTED_SMALL_TEXTBOX),
	2955: dataclasses.replace(ParseSettingsPresets.DEFAULT_NEW_ENCHANTED_PARSE_SETTINGS, cardLayout=CardLayout.NEW_ENCHANTED_SMALL_TEXTBOX),
	2956: dataclasses.replace(ParseSettingsPresets.DEFAULT_ENCHANTED_PARSE_SETTINGS, labelParsingMethod=LABEL_PARSING_METHODS.FALLBACK_WHITE_ABILITY_TEXT, cardTextHasOutline=False, labelIsDarkerThanBackground=False,
							  labelTextColor=ImageArea.TEXT_COLOUR_MIDDLE, thresholdTextColor=ImageArea.TEXT_COLOUR_MIDDLE, textboxLeftOffset=25),
	2957: dataclasses.replace(ParseSettingsPresets.DEFAULT_ENCHANTED_PARSE_SETTINGS, labelParsingMethod=LABEL_PARSING_METHODS.FALLBACK_BY_LINES, labelIsDarkerThanBackground=False,
							  labelTextColor=ImageArea.TEXT_COLOUR_MIDDLE, thresholdTextColor=ImageArea.TEXT_COLOUR_MIDDLE, textboxLeftOffset=25),
	2958: dataclasses.replace(ParseSettingsPresets.DEFAULT_PARSE_SETTINGS, labelIsDarkerThanBackground=False, thresholdTextColor=ImageArea.TEXT_COLOUR_WHITE, labelMaskColor=ParseSettingConstants.BLACK),
	2959: dataclasses.replace(ParseSettingsPresets.DEFAULT_PARSE_SETTINGS, labelIsDarkerThanBackground=False, thresholdTextColor=ImageArea.TEXT_COLOUR_WHITE, labelMaskColor=ParseSettingConstants.BLACK),
	2960: dataclasses.replace(ParseSettingsPresets.DEFAULT_PARSE_SETTINGS, labelIsDarkerThanBackground=False, thresholdTextColor=ImageArea.TEXT_COLOUR_WHITE, labelMaskColor=ParseSettingConstants.BLACK),
	2961: dataclasses.replace(ParseSettingsPresets.DEFAULT_PARSE_SETTINGS, labelIsDarkerThanBackground=False, thresholdTextColor=ImageArea.TEXT_COLOUR_WHITE, labelMaskColor=ParseSettingConstants.BLACK),
	2962: dataclasses.replace(ParseSettingsPresets.DEFAULT_PARSE_SETTINGS, labelIsDarkerThanBackground=False, thresholdTextColor=ImageArea.TEXT_COLOUR_WHITE, labelMaskColor=ParseSettingConstants.BLACK),
	2963: dataclasses.replace(ParseSettingsPresets.DEFAULT_PARSE_SETTINGS, labelIsDarkerThanBackground=False, thresholdTextColor=ImageArea.TEXT_COLOUR_WHITE, labelMaskColor=ParseSettingConstants.BLACK),
	2964: dataclasses.replace(ParseSettingsPresets.DEFAULT_PARSE_SETTINGS, labelIsDarkerThanBackground=False, thresholdTextColor=ImageArea.TEXT_COLOUR_WHITE, labelMaskColor=ParseSettingConstants.BLACK),
	2965: dataclasses.replace(ParseSettingsPresets.DEFAULT_PARSE_SETTINGS, labelIsDarkerThanBackground=False, thresholdTextColor=ImageArea.TEXT_COLOUR_WHITE, labelMaskColor=ParseSettingConstants.BLACK),
	2966: dataclasses.replace(ParseSettingsPresets.DEFAULT_PARSE_SETTINGS, labelIsDarkerThanBackground=False, thresholdTextColor=ImageArea.TEXT_COLOUR_WHITE, labelMaskColor=ParseSettingConstants.BLACK),
	2968: dataclasses.replace(ParseSettingsPresets.DEFAULT_PARSE_SETTINGS, textboxLeftOffset=40),
	2969: dataclasses.replace(ParseSettingsPresets.DEFAULT_PARSE_SETTINGS, textboxLeftOffset=40),
	2971: ParseSettingsPresets.DEFAULT_EPIC_PARSE_SETTINGS,
	3204: dataclasses.replace(ParseSettingsPresets.PARSE_SETTINGS_FOR_ENCHANTED_BY_SET["13"], characterCardLayout=CardLayout.NEW_ENCHANTED_CHARACTER_SMALL_TEXTBOX),
	3207: dataclasses.replace(ParseSettingsPresets.PARSE_SETTINGS_FOR_ENCHANTED_BY_SET["13"], characterCardLayout=CardLayout.NEW_ENCHANTED_CHARACTER_SMALL_TEXTBOX),
	3211: dataclasses.replace(ParseSettingsPresets.PARSE_SETTINGS_FOR_ENCHANTED_BY_SET["13"], textboxLeftOffset=-20, thresholdTextColor=ImageArea.TEXT_COLOUR_WHITE_LIGHT_BACKGROUND),
	3215: dataclasses.replace(ParseSettingsPresets.DEFAULT_ICONIC_PARSE_SETTINGS, colorFilterLowerBound=(0, 130, 200), colorFilterUpperBound=(60, 180, 250), textboxTopOffset=255, textboxRightOffset=760, textboxBottomOffset=-20,
							  typeImageVerticalOffset=-45, typeImageLeftOffset=50, typeImageRightOffset=-500),
	3216: dataclasses.replace(ParseSettingsPresets.DEFAULT_ICONIC_PARSE_SETTINGS, colorFilterLowerBound=(100, 80, 0), colorFilterUpperBound=(190, 135, 50), textboxTopOffset=100),
	3217: dataclasses.replace(ParseSettingsPresets.DEFAULT_PARSE_SETTINGS, labelIsDarkerThanBackground=False, thresholdTextColor=ImageArea.TEXT_COLOUR_WHITE, labelMaskColor=ParseSettingConstants.BLACK, textboxBottomOffset=-80),
	3218: dataclasses.replace(ParseSettingsPresets.DEFAULT_PARSE_SETTINGS, labelIsDarkerThanBackground=False, thresholdTextColor=ImageArea.TEXT_COLOUR_WHITE, labelMaskColor=ParseSettingConstants.BLACK, textboxBottomOffset=-80),
	3219: dataclasses.replace(ParseSettingsPresets.DEFAULT_PARSE_SETTINGS, labelIsDarkerThanBackground=False, thresholdTextColor=ImageArea.TEXT_COLOUR_WHITE, labelMaskColor=ParseSettingConstants.BLACK, textboxBottomOffset=-80),
	3221: ParseSettingsPresets.PARSE_SETTINGS_BY_GROUPING["PD1"],
	3222: ParseSettingsPresets.PARSE_SETTINGS_BY_GROUPING["PD1"],
	3225: dataclasses.replace(ParseSettingsPresets.DEFAULT_PARSE_SETTINGS, textboxLeftOffset=10),
	3226: dataclasses.replace(ParseSettingsPresets.DEFAULT_PARSE_SETTINGS, textboxLeftOffset=10, labelParsingMethod=LABEL_PARSING_METHODS.FALLBACK_BY_LINES),
	3237: dataclasses.replace(ParseSettingsPresets.PARSE_SETTINGS_BY_GROUPING["CC1"], typeImageTextColorOverride=ImageArea.TEXT_COLOUR_WHITE_LIGHT_BACKGROUND),
	3238: dataclasses.replace(ParseSettingsPresets.PARSE_SETTINGS_BY_GROUPING["CC1"], characterCardLayout=CardLayout.NEW_ENCHANTED_CHARACTER_SMALL_TEXTBOX, lineParsingMaxGap=7, textboxTopOffset=-60),
	3242: dataclasses.replace(ParseSettingsPresets.PARSE_SETTINGS_BY_GROUPING["CC1"], artistRightOffset=-200),
	3249: dataclasses.replace(ParseSettingsPresets.PARSE_SETTINGS_BY_GROUPING["P3"], labelStartThreshold=100, labelEndThreshold=170, labelTextColor=ImageArea.TEXT_COLOUR_MIDDLE, textboxLeftOffset=10),
	3506: dataclasses.replace(ParseSettingsPresets.DEFAULT_STANDARDSIZED_ICONIC_PARSE_SETTINGS, colorFilterLowerBound=(50, 150, 220), colorFilterUpperBound=(165, 210, 256), textboxTopOffset=170, textboxRightOffset=100,
							  typeImageVerticalOffset=-40, typeImageRightOffset=-450, typeImageTextColorOverride=ImageArea.TEXT_COLOUR_WHITE),
	3507: dataclasses.replace(ParseSettingsPresets.DEFAULT_STANDARDSIZED_ICONIC_PARSE_SETTINGS, colorFilterLowerBound=(134, 90, 0), colorFilterUpperBound=(195, 136, 25), textboxBottomOffset=20),
	3585: ParseSettingsPresets.DEFAULT_PARSE_SETTINGS,
	3586: dataclasses.replace(ParseSettingsPresets.PARSE_SETTINGS_BY_GROUPING["D23"], labelTextColor=ImageArea.TEXT_COLOUR_WHITE_LIGHT_BACKGROUND),
	3587: dataclasses.replace(ParseSettingsPresets.PARSE_SETTINGS_BY_GROUPING["D23"], labelTextColor=ImageArea.TEXT_COLOUR_WHITE_LIGHT_BACKGROUND, artistRightOffset=-350),
	3588: dataclasses.replace(ParseSettingsPresets.PARSE_SETTINGS_BY_GROUPING["D23"], labelTextColor=ImageArea.TEXT_COLOUR_WHITE_LIGHT_BACKGROUND),
	3589: dataclasses.replace(ParseSettingsPresets.PARSE_SETTINGS_BY_GROUPING["D23"], forceArtistTextColor=ImageArea.TEXT_COLOUR_WHITE_LIGHT_BACKGROUND, labelTextColor=ImageArea.TEXT_COLOUR_WHITE_LIGHT_BACKGROUND),
	3590: dataclasses.replace(ParseSettingsPresets.PARSE_SETTINGS_BY_GROUPING["D23"], artistRightOffset=-200, labelTextColor=ImageArea.TEXT_COLOUR_WHITE_LIGHT_BACKGROUND),
	3591: dataclasses.replace(ParseSettingsPresets.PARSE_SETTINGS_BY_GROUPING["D23"], textboxBottomOffset=-70, labelTextColor=ImageArea.TEXT_COLOUR_WHITE_LIGHT_BACKGROUND),
	3594: dataclasses.replace(ParseSettingsPresets.DEFAULT_PARSE_SETTINGS, textboxLeftOffset=25, textboxTopOffset=30, textboxBottomOffset=-30, typeImageLeftOffset=-50, typeImageRightOffset=-700,
							  thresholdTextColor=ImageArea.TEXT_COLOUR_MIDDLE),
}
